# Generated by Django 4.2.9 on 2026-03-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('claim_submitted', 'Zgłoszono szkodę'), ('claim_status_changed', 'Zmiana statusu szkody'), ('policy_status_changed', 'Zmiana statusu polisy'), ('policy_expiring', 'Polisa wygasa wkrótce'), ('additional_info', 'Wymagane uzupełnienie dokumentów'), ('claim_approved', 'Szkoda zatwierdzona'), ('claim_rejected', 'Szkoda odrzucona'), ('claim_paid', 'Szkoda wypłacona')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('related_claim_id', models.IntegerField(blank=True, null=True)),
                ('related_policy_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'ordering': ['-created_at'],
            },
        ),
    ]
