# Generated by Django 4.2.9 on 2026-03-17 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(editable=False, max_length=25, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('submitted', 'Zgłoszona'), ('under_review', 'W trakcie oceny'), ('additional_info', 'Oczekuje na uzupełnienie'), ('approved', 'Zatwierdzona'), ('partially_approved', 'Częściowo zatwierdzona'), ('rejected', 'Odrzucona'), ('paid', 'Wypłacona'), ('closed', 'Zamknięta')], default='draft', max_length=25)),
                ('incident_type', models.CharField(choices=[('accident', 'Wypadek'), ('theft', 'Kradzież'), ('fire', 'Pożar'), ('flood', 'Powódź'), ('vandalism', 'Wandalizm'), ('illness', 'Choroba'), ('injury', 'Uraz'), ('natural_disaster', 'Klęska żywiołowa'), ('other', 'Inne')], max_length=25)),
                ('incident_date', models.DateField()),
                ('incident_location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('estimated_damage', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('agent_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Szkoda',
                'verbose_name_plural': 'Szkody',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('photo', 'Zdjęcie'), ('police_report', 'Protokół policyjny'), ('medical_report', 'Dokumentacja medyczna'), ('repair_estimate', 'Kosztorys naprawy'), ('invoice', 'Faktura'), ('other', 'Inne')], max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='claim_documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dokument szkody',
                'verbose_name_plural': 'Dokumenty szkody',
            },
        ),
        migrations.CreateModel(
            name='ClaimStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historia statusu szkody',
                'verbose_name_plural': 'Historii statusów szkód',
                'ordering': ['-changed_at'],
            },
        ),
    ]
