# Generated by Django 4.2.9 on 2026-03-17 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('auto', 'Ubezpieczenie pojazdu'), ('property', 'Ubezpieczenie majątkowe'), ('health', 'Ubezpieczenie zdrowotne'), ('life', 'Ubezpieczenie na życie'), ('travel', 'Ubezpieczenie podróżne'), ('liability', 'Ubezpieczenie OC')], max_length=20)),
                ('description', models.TextField()),
                ('coverage_details', models.JSONField(default=dict)),
                ('base_price_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produkt ubezpieczeniowy',
                'verbose_name_plural': 'Produkty ubezpieczeniowe',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Oczekująca na aktywację'), ('active', 'Aktywna'), ('expired', 'Wygasła'), ('cancelled', 'Anulowana'), ('suspended', 'Zawieszona')], default='pending', max_length=20)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('premium_monthly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('insured_object', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Polisa',
                'verbose_name_plural': 'Polisy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Umowa'), ('amendment', 'Aneks'), ('certificate', 'Certyfikat'), ('other', 'Inne')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='policy_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='policies.policy')),
            ],
            options={
                'verbose_name': 'Dokument polisy',
                'verbose_name_plural': 'Dokumenty polisy',
            },
        ),
    ]
